### ISSUE TITLE
Go get doesn't work without libgit2 dependency

### ISSUE THREAD

**Issue by nordicdyno** [askgitdev/askgit#131]
it would be nice to mention libgit2 requirement in README

My environment: macOS Big Sur, go1.16.5 darwin/amd64

**Comment by patrickdevivo** [comment]
Yes, this is a good point, thanks for bringing it up! We have some rather large structural changes on the way (#132) which will warrant a README update as well (some table schemas will change) - I will include an update to document the `libgit2` requirement when we make those README changes 👍
