### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by wi1dcard** [askgitdev/askgit#138]
Hey team, thank you for providing this awesome tool which helps me a lot traversing the data in git repos. I'm wondering that do we have any plan to add binaries in the GitHub releases (for example, on GitHub Actions)? It seems not so friendly to the new users who have to build from source to install and try.

**Comment by patrickdevivo** [comment]
Should be addressed in #139 - at least a start anyways! Thanks for bringing it up, it's been on the backburner for some time and definitely makes sense to do.
